const STATIONS={
  ct_greenwich:{id:'8469549',name:'Cos Cob Harbor / Greenwich'},ct_stamford:{id:'8469198',name:'Stamford Harbor'},ct_rowayton:{id:'8468609',name:'Rowayton / Five Mile River'},ct_norwalk:{id:'8468448',name:'South Norwalk'},ct_saugatuck:{id:'8468191',name:'Saugatuck River'},ct_blackrock:{id:'8467373',name:'Black Rock Harbor'},ct_bridgeport:{id:'8467150',name:'Bridgeport'},ct_stratford:{id:'8466797',name:'Stratford / I-95 Bridge'},
  nj_sandy:{id:'8531712',name:'Highlands / Route 36'},nj_seabright:{id:'8531804',name:'Sea Bright'},nj_redbank:{id:'8531833',name:'Red Bank'},nj_shark:{id:'8532322',name:'Shark River Hills'},nj_manasquan:{id:'8532591',name:'Manasquan Inlet'}
};
const P=[
{r:'fairfield',id:'lescale',name:"L'escale at Delamar",town:'Greenwich',water:'Greenwich Harbor',lat:41.01783,lon:-73.62383,s:'ct_greenwich',access:'Delamar private marina',dock:8,approach:9,phone:'203-733-5320',vhf:'9 / 78',url:'https://lescalerestaurant.com/',e:'https://www.delamar.com/hotels/delamar-greenwich-harbor/greenwich-marina',src:'Delamar Greenwich Harbor Marina',note:'Private marina access at the hotel/restaurant. Published directory baseline: 9 ft approach / 8 ft dockside; confirm assigned slip and sounding.'},
{r:'fairfield',id:'prime',name:'Prime: An American Kitchen & Bar',town:'Stamford',water:'Stamford Harbor',lat:41.03833,lon:-73.54500,s:'ct_stamford',access:'Harbor Point West Dock & Dine',dock:8,approach:12,phone:'203-355-6045',vhf:'9',url:'https://stamford.restaurantprime.com/',e:'https://harborpointmarinas.com/transient-slips-stamford-ct/',src:'Harbor Point Marinas',note:'Official Harbor Point Dock & Dine option. Slip assignment comes from the dockmaster.'},
{r:'fairfield',id:'wheel',name:'The Wheel',town:'Stamford',water:'Harbor Point East',lat:41.04130,lon:-73.53086,s:'ct_stamford',access:'Harbor Point Dock & Dine',dock:6,approach:10,phone:'203-355-6045',vhf:'9',url:'https://www.thevillagewheel.com/',e:'https://harborpointmarinas.com/transient-slips-stamford-ct/',src:'Harbor Point Marinas',note:'Official Harbor Point Dock & Dine option; directory baseline 10 ft approach / 6 ft dockside.'},
{r:'fairfield',id:'fortina',name:'Fortina Stamford',town:'Stamford',water:'Harbor Point North',lat:41.04050,lon:-73.54370,s:'ct_stamford',access:'Harbor Point Dock & Dine',dock:6,approach:10,phone:'203-355-6045',vhf:'9',url:'https://fortinapizza.com/',e:'https://harborpointmarinas.com/transient-slips-stamford-ct/',src:'Harbor Point Marinas',note:'Marina-access dining via Harbor Point North.'},
{r:'fairfield',id:'whale',name:'Sign of the Whale',town:'Stamford',water:'Harbor Point North',lat:41.04015,lon:-73.54325,s:'ct_stamford',access:'Harbor Point Dock & Dine',dock:6,approach:10,phone:'203-355-6045',vhf:'9',url:'https://www.signofthewhalect.com/',e:'https://harborpointmarinas.com/transient-slips-stamford-ct/',src:'Harbor Point Marinas',note:'Official Harbor Point Dock & Dine option.'},
{r:'fairfield',id:'bareburger',name:'Bareburger Stamford',town:'Stamford',water:'Harbor Point North',lat:41.03985,lon:-73.54280,s:'ct_stamford',access:'Harbor Point Dock & Dine',dock:6,approach:10,phone:'203-355-6045',vhf:'9',url:'https://bareburger.com/locations/stamford/',e:'https://harborpointmarinas.com/transient-slips-stamford-ct/',src:'Harbor Point Marinas',note:'Official Harbor Point Dock & Dine option.'},
{r:'fairfield',id:'rowayton',name:'Rowayton Seafood',town:'Rowayton / Norwalk',water:'Five Mile River',lat:41.06470,lon:-73.44520,s:'ct_rowayton',access:'Restaurant slips · reservation required',dock:null,approach:7,phone:'203-866-4488',vhf:'68 peak',url:'https://www.rowaytonseafood.com/',e:'https://www.rowaytonseafood.com/dock-1',src:'Rowayton Seafood',note:'Very limited slips with confirmation required. No current restaurant-dock sounding is published; approach value is context only.'},
{r:'fairfield',id:'harborlights',name:'Harbor Lights',town:'Norwalk',water:'Norwalk Harbor',lat:41.09110,lon:-73.41400,s:'ct_norwalk',access:'Restaurant customer dock',dock:null,approach:null,phone:'203-866-3364',vhf:'Call venue',url:'https://harborlightsrestaurant-ct.com/',e:'https://harborlightsrestaurant-ct.com/',src:'Harbor Lights',note:'The restaurant explicitly welcomes boat arrivals. Tide shown; no dock depth is manufactured.'},
{r:'fairfield',id:'sunset',name:'Sunset Grille at Norwalk Cove',town:'Norwalk',water:'Norwalk Harbor',lat:41.08395,lon:-73.39999,s:'ct_norwalk',access:'Norwalk Cove Marina transient access',dock:9,approach:9,phone:'203-838-5899',vhf:'9 / 72',url:'https://www.sunsetgrille.net/',e:'https://www.norwalkcove.com/',src:'Norwalk Cove Marina',note:'On-site restaurant in Norwalk Cove Marina; published planning baseline 9 ft approach / dockside.'},
{r:'fairfield',id:'sono',name:'SoNo Seaport Seafood',town:'South Norwalk',water:'Norwalk River',lat:41.09820,lon:-73.41350,s:'ct_norwalk',access:'Municipal visitor docks · short walk',dock:8,approach:12,phone:'203-866-8810',vhf:'9',url:'https://www.sonoseaportseafood.com/',e:'https://www.norwalkct.gov/306/Norwalk-Visitors-Docks',src:'City of Norwalk Visitor Docks',note:'Uses nearby municipal transient docks rather than an assumed restaurant-owned slip.'},
{r:'fairfield',id:'bridge',name:'The Bridge at Saugatuck',town:'Westport',water:'Saugatuck River',lat:41.11950,lon:-73.36950,s:'ct_saugatuck',access:'8 private restaurant slips',dock:null,approach:1,phone:'203-557-0984',vhf:'Call on approach',url:'https://www.thebridgesaugatuck.com/',e:'https://www.thebridgesaugatuck.com/blog/dock-dine-at-the-bridge-boat-up-restaurant-westport-connecticut-x2cdg',src:'The Bridge',note:'Eight dining slips. Saugatuck is intentionally treated conservatively because of shoaling; favor a rising tide and local knowledge.'},
{r:'fairfield',id:'whelk',name:'The Whelk',town:'Westport',water:'Saugatuck River',lat:41.12230,lon:-73.37020,s:'ct_saugatuck',access:'3 customer slips · boats to 33 ft',dock:null,approach:1,phone:'203-557-0902',vhf:'Call ahead',url:'https://thewhelkwestport.com/',e:'https://thewhelkwestport.com/contact',src:'The Whelk',note:'Three first-come slips. Conservative approach baseline reflects channel shoaling warning, not measured restaurant-slip depth.'},
{r:'fairfield',id:'captains',name:"Captain's Cove Seaport Restaurant",town:'Bridgeport',water:'Black Rock Harbor',lat:41.15733,lon:-73.21417,s:'ct_blackrock',access:'Captain’s Cove transient dock',dock:13,approach:18,phone:'203-335-1433',vhf:'18',url:'https://www.captainscoveseaport.com/lower-deck-menu',e:'https://www.captainscoveseaport.com/marina',src:"Captain's Cove",note:'Transient dock with on-site seasonal waterfront restaurant.'},
{r:'fairfield',id:'boca',name:'Boca Oyster Bar',town:'Bridgeport',water:'Bridgeport Harbor',lat:41.17420,lon:-73.18040,s:'ct_bridgeport',access:'Bridgeport Harbor Marina Dock & Dine',dock:12,approach:25,phone:'203-330-8787',vhf:'9',url:'https://bocaoysterbar.com/',e:'https://bridgeportharbormarina.com/service/dock-and-dine/',src:'Bridgeport Harbor Marina',note:'Proceed to Dock A and contact the dockmaster; restaurant reservations recommended.'},
{r:'fairfield',id:'outriggers',name:'Outriggers',town:'Stratford',water:'Housatonic River',lat:41.18893,lon:-73.12077,s:'ct_stratford',access:'Safe Harbor Stratford transient slips',dock:12,approach:15,phone:'203-377-4477',vhf:'9',url:'https://outriggersrestaurant.com/',e:'https://safeharbor.com/locations/safe-harbor-stratford/',src:'Safe Harbor Stratford',note:'On-site restaurant at Safe Harbor Stratford. River current can be strong.'},
{r:'fairfield',id:'joey',name:"Joey C's Boathouse",town:'Stratford',water:'Housatonic River',lat:41.20250,lon:-73.11100,s:'ct_stratford',access:'Boardwalk Marina · on-site dining',dock:12,approach:13,phone:'203-378-9300',vhf:'9',url:'https://www.joeycsboathouse.com/',e:'https://boardwalkmarinact.com/',src:'Boardwalk Marina',note:'On-site dining with marina access; call for transient availability and current river conditions.'},
{r:'monmouth',id:'ondeck',name:'On the Deck',town:'Atlantic Highlands',water:'Atlantic Highlands Harbor',lat:40.41770,lon:-74.03612,s:'nj_sandy',access:'Municipal transient berths',dock:null,approach:null,phone:'732-872-1424',vhf:'Harbor',url:'https://onthedeckrestaurant.com/',e:'https://www.ahnj.com/ahnj/Harbor/Amenities',src:'Atlantic Highlands municipal harbor',note:'Secure a transient harbor berth first, then walk to the restaurant.'},
{r:'monmouth',id:'onewillow',name:'One Willow',town:'Highlands',water:'Sandy Hook Bay',lat:40.4094,lon:-74.0006,s:'nj_sandy',access:'15 transient / Dock & Dine slips',dock:6,approach:null,phone:'732-872-1511',vhf:'7',url:'https://www.onewillowhighlands.com/',e:'https://sandyhookbaymarina.com/marina/',src:'Sandy Hook Bay Marina',note:'Complimentary Dock & Dine slips when available; published 6 ft low-water marina depth.'},
{r:'monmouth',id:'bahrs',name:'Bahr’s Landing',town:'Highlands',water:'Shrewsbury River mouth',lat:40.39733,lon:-73.98082,s:'nj_sandy',access:'Bahr’s Marina',dock:null,approach:null,phone:'732-872-1245',vhf:'Dockmaster',url:'https://bahrslanding.com/',e:'https://bahrslanding.com/dock-dine/',src:'Bahr’s Landing',note:'Official Dock & Dine access; current dockside depth is not published clearly enough for a numeric estimate.'},
{r:'monmouth',id:'mobys',name:'Moby’s Lobster Deck',town:'Highlands',water:'Shrewsbury River mouth',lat:40.3971,lon:-73.9802,s:'nj_sandy',access:'Bahr’s Marina / Moby’s',dock:null,approach:null,phone:'732-872-1245 x4',vhf:'Dockmaster',url:'https://www.mobyslobsterdeck.com/',e:'https://bahrslanding.com/dock-dine/',src:'Bahr’s Landing',note:'Uses the same marina property as Bahr’s; confirm berth assignment before arrival.'},
{r:'monmouth',id:'seafarer',name:'The Seafarer',town:'Highlands',water:'Sandy Hook Bay',lat:40.40537,lon:-73.98858,s:'nj_sandy',access:'1 designated + two T-docks',dock:null,approach:null,phone:'732-861-1741',vhf:'Call venue',url:'https://www.seafarernj.com/',e:'https://www.seafarernj.com/dock-n-dine',src:'The Seafarer',note:'One designated slip for boats under 22 ft plus tie-up on two T-docks.'},
{r:'monmouth',id:'beachwalk',name:'TheBAR at BeachWalk / Taco Shell',town:'Sea Bright',water:'Shrewsbury River',lat:40.3877,lon:-73.9740,s:'nj_seabright',access:'Private seasonal dock',dock:null,approach:null,phone:'732-842-8450',vhf:'Call venue',url:'https://www.beachwalkseabright.com/',e:'https://www.beachwalkseabright.com/',src:'BeachWalk',note:'Current site welcomes guests arriving by boat; confirm seasonal dock conditions.'},
{r:'monmouth',id:'cove',name:'The Cove',town:'Sea Bright',water:'Shrewsbury River',lat:40.35737,lon:-73.97470,s:'nj_seabright',access:'Covesail transient slips',dock:null,approach:null,phone:'732-842-5319',vhf:'68 / 9',url:'https://thecoveseabright.com/',e:'https://thecoveseabright.com/',src:'The Cove / Covesail',note:'Secure dockage with Covesail Marina before arrival.'},
{r:'monmouth',id:'eventide',name:'EvenTide Grille',town:'Sea Bright',water:'Shrewsbury River',lat:40.35116,lon:-73.97637,s:'nj_seabright',access:'Navesink Marina transient slips',dock:null,approach:null,phone:'732-842-3700',vhf:'Call marina',url:'https://eventidegrille.com/',e:'https://www.navesinkmarina.com/',src:'Navesink Marina',note:'On-site dining via Navesink Marina transient slips.'},
{r:'monmouth',id:'beachtavern',name:'Beach Tavern',town:'Monmouth Beach',water:'Shrewsbury River',lat:40.33667,lon:-73.98117,s:'nj_seabright',access:'Private pier',dock:null,approach:null,phone:'732-870-8999',vhf:'Dockmaster',url:'https://beachtavernnj.com/',e:'https://beachtavernnj.com/about/',src:'Beach Tavern',note:'Call the dockmaster about 30 minutes before arrival.'},
{r:'monmouth',id:'molo',name:'Osteria Molo',town:'Monmouth Beach',water:'Shrewsbury River',lat:40.33655,lon:-73.9813,s:'nj_seabright',access:'5 Channel Club transient slips',dock:null,approach:null,phone:'732-222-7717',vhf:'Marina',url:'https://osteriamolonj.com/',e:'https://channelclubmarina.com/boats/',src:'Channel Club Marina',note:'Reserve a transient slip with Channel Club Marina first.'},
{r:'monmouth',id:'molly',name:'Molly Pitcher Inn',town:'Red Bank',water:'Navesink River',lat:40.35333,lon:-74.07233,s:'nj_redbank',access:'72-slip marina · transient welcomed',dock:6,approach:null,phone:'732-747-2500 x535',vhf:'9',url:'https://www.themollypitcher.com/',e:'https://themollypitcher.com/marina/',src:'Molly Pitcher Marina',note:'Dock & Dine reservations required; published 6 ft low-water planning baseline.'},
{r:'monmouth',id:'oyster',name:'Pearl at The Oyster Point Hotel',town:'Red Bank',water:'Navesink River',lat:40.35537,lon:-74.07427,s:'nj_redbank',access:'34 overnight / Dock & Dine slips',dock:null,approach:null,phone:'732-530-8200',vhf:'9',url:'https://www.theoysterpointhotel.com/',e:'https://www.theoysterpointhotel.com/about-us/marina/',src:'Oyster Point Marina',note:'Dock & Dine reservations required; handles vessels up to roughly 60 ft.'},
{r:'monmouth',id:'marinagrille',name:'Marina Grille',town:'Belmar',water:'Shark River',lat:40.1809,lon:-74.0310,s:'nj_shark',access:'Belmar Marina dock access',dock:7,approach:null,phone:'732-894-3211',vhf:'Belmar Marina',url:'https://marinagrillenj.com/',e:'https://www.marinagrillenj.com/',src:'Marina Grille',note:'Official dock + dine access at Belmar Marina; published planning baseline 7 ft MLW.'},
{r:'monmouth',id:'pier9',name:'9th Ave Pier',town:'Belmar',water:'Shark River',lat:40.1808,lon:-74.0307,s:'nj_shark',access:'Belmar Marina guest dock space',dock:7,approach:null,phone:'732-749-3800',vhf:'Belmar Marina',url:'https://www.9thavepier.com/',e:'https://www.9thavepier.com/faq',src:'9th Ave Pier',note:'Official FAQ says dock space is available for guests wishing to dock and dine.'},
{r:'monmouth',id:'waypoint',name:'Waypoint 622',town:'Brielle',water:'Manasquan River',lat:40.10742,lon:-74.05186,s:'nj_manasquan',access:'1 first-come Dock & Dine slip',dock:null,approach:null,phone:'732-528-6665',vhf:'Call once on site',url:'https://www.waypoint622.com/',e:'https://www.waypoint622.com/location/waypoint-662/',src:'Waypoint 622',note:'One first-come Dock & Dine slip; call to check availability once there.'}
];
const $=id=>document.getElementById(id);const H=3600e3;let region='all',map,markers={};const tideCache={};
function ep(ms){const a=new Intl.DateTimeFormat('en-US',{timeZone:'America/New_York',year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',hourCycle:'h23'}).formatToParts(new Date(ms));const g=t=>a.find(x=>x.type===t)?.value||'';return{y:g('year'),m:g('month'),d:g('day'),h:g('hour'),min:g('minute')}}
function easternMs(s){const m=s.match(/(\d{4})-(\d\d)-(\d\d)[ T](\d\d):(\d\d)/);if(!m)return Date.now();const g=Date.UTC(+m[1],+m[2]-1,+m[3],+m[4],+m[5]);const p=new Intl.DateTimeFormat('en-US',{timeZone:'America/New_York',year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',hourCycle:'h23'}).formatToParts(new Date(g));const q=t=>+p.find(x=>x.type===t).value;const r=Date.UTC(q('year'),q('month')-1,q('day'),q('hour'),q('minute'));return g-(r-g)}
function defaultArrival(){const p=ep(Math.ceil(Date.now()/(30*60e3))*30*60e3);return`${p.y}-${p.m}-${p.d}T${p.h}:${p.min}`}
function arrMs(){return easternMs($('arrival').value||defaultArrival())}function req(){return(+$('draft').value||0)+(+$('ukc').value||0)}function ymd(ms){const p=ep(ms);return`${p.y}${p.m}${p.d}`}
async function fetchTide(key){const s=STATIONS[key],center=arrMs(),start=center-18*H,end=center+30*H;const call=async interval=>{const q=new URLSearchParams({product:'predictions',application:'dock-dine-unified',begin_date:ymd(start),end_date:ymd(end),datum:'MLLW',station:s.id,time_zone:'lst_ldt',units:'english',format:'json',interval});const r=await fetch('https://api.tidesandcurrents.noaa.gov/api/prod/datagetter?'+q);const j=await r.json().catch(()=>null);if(!r.ok||!j?.predictions?.length)throw Error('NOAA');return j.predictions};let points,mode='6';try{points=await call('6')}catch{points=await call('hilo');mode='hilo'};tideCache[key]={mode,points:points.map(p=>({t:easternMs(p.t),v:+p.v,type:p.type||''})).filter(p=>Number.isFinite(p.t)&&Number.isFinite(p.v)).sort((a,b)=>a.t-b.t)}}
function valueAt(series,ms){const a=series?.points||[];if(!a.length)return NaN;if(ms<=a[0].t)return a[0].v;if(ms>=a[a.length-1].t)return a[a.length-1].v;let x=a[0],z=a[a.length-1];for(let i=1;i<a.length;i++)if(a[i].t>=ms){x=a[i-1];z=a[i];break}let f=(ms-x.t)/(z.t-x.t);if(series.mode==='hilo')f=(1-Math.cos(Math.PI*f))/2;return x.v+(z.v-x.v)*f}
function fmt(ms){return new Date(ms).toLocaleString([],{timeZone:'America/New_York',month:'short',day:'numeric',hour:'numeric',minute:'2-digit'})}function ft(v){return Number.isFinite(v)?v.toFixed(1)+' ft':'—'}
function visible(){const q=$('search').value.trim().toLowerCase();return P.filter(p=>(region==='all'||p.r===region)&&(!q||(`${p.name} ${p.town} ${p.water}`).toLowerCase().includes(q)))}
function chart(p){const s=tideCache[p.s],c=arrMs();if(!s?.points?.length)return'';const start=c-12*H,end=c+12*H,samp=[];for(let t=start;t<=end;t+=15*60e3){const v=valueAt(s,t);if(Number.isFinite(v))samp.push({t,v})}if(!samp.length)return'';let vals=samp.map(x=>x.v);const threshold=Number.isFinite(p.dock)?req()-p.dock:NaN;if(Number.isFinite(threshold))vals.push(threshold);let lo=Math.min(...vals),hi=Math.max(...vals),pad=Math.max(.25,(hi-lo)*.12);lo-=pad;hi+=pad;const X=t=>10+300*(t-start)/(end-start),Y=v=>82-68*(v-lo)/(hi-lo||1);const path=samp.map((x,i)=>`${i?'L':'M'}${X(x.t).toFixed(1)},${Y(x.v).toFixed(1)}`).join(' ');const th=Number.isFinite(threshold)&&threshold>=lo&&threshold<=hi?`<line x1="10" y1="${Y(threshold)}" x2="310" y2="${Y(threshold)}" stroke="#9a651f" stroke-width="1.3" stroke-dasharray="4 4"/>`:'';return`<div class="chartwrap"><div class="charthead"><b>24-hour tide window</b><span>${s.mode==='hilo'?'NOAA H/L · curve estimated':'NOAA 6-min predictions'}</span></div><svg class="chart" viewBox="0 0 320 92" role="img"><line x1="10" y1="82" x2="310" y2="82" stroke="#cbd6d8"/>${th}<line x1="160" y1="8" x2="160" y2="84" stroke="#617a80" stroke-dasharray="3 4"/><path d="${path}" fill="none" stroke="#15718a" stroke-width="2.3"/><text x="10" y="91" font-size="8" fill="#667b80">−12h</text><text x="160" y="91" text-anchor="middle" font-size="8" fill="#425f66">arrival</text><text x="310" y="91" text-anchor="end" font-size="8" fill="#667b80">+12h</text></svg></div>`}
function card(p){const s=tideCache[p.s],t=valueAt(s,arrMs()),dock=Number.isFinite(p.dock)&&Number.isFinite(t)?p.dock+t:NaN,approach=Number.isFinite(p.approach)&&Number.isFinite(t)?p.approach+t:NaN,control=[dock,approach].filter(Number.isFinite);const controlling=control.length?Math.min(...control):NaN,clear=Number.isFinite(controlling)?controlling-(+$('draft').value||0):NaN,ukc=+$('ukc').value||0;let cls='unknown',text='Tide shown; dock/approach baseline incomplete';if(Number.isFinite(clear)){cls=clear>=ukc+1?'ok':clear>=ukc?'caution':'no';text=clear>=ukc+1?`Estimated UKC ${clear.toFixed(1)} ft · ≥1 ft above selected margin`:clear>=ukc?`Estimated UKC ${clear.toFixed(1)} ft · meets selected minimum narrowly`:`Estimated UKC ${clear.toFixed(1)} ft · below selected minimum`}return`<article class="card"><div class="cardhead"><div class="cardtitle"><div><h3>${p.name}</h3><div class="place-meta">${p.town} · ${p.water}</div></div><span class="regiontag ${p.r}">${p.r==='fairfield'?'Fairfield CT':'Monmouth NJ'}</span></div></div><div class="cardbody"><div class="stats"><div class="stat"><span>Access</span><b>${p.access}</b></div><div class="stat"><span>Phone / VHF</span><b>${p.phone} · ${p.vhf}</b></div></div><div class="water"><div class="waterrow"><div><div class="waterlabel">Predicted tide at arrival</div><div class="waternum">${ft(t)} MLLW</div></div><div style="text-align:right"><div class="waterlabel">Controlling est. depth</div><div class="waternum">${ft(controlling)}</div></div></div><div class="status ${cls}">${text}</div></div>${chart(p)}<div class="note">${p.note}</div><div class="source">Access source: <a href="${p.e}" target="_blank" rel="noopener">${p.src}</a></div><div class="actions"><button class="btn" onclick="focusPlace('${p.r}:${p.id}')">Map</button><a class="btn secondary" href="${p.url}" target="_blank" rel="noopener">Venue</a></div></div></article>`}
function render(){const v=visible();$('cards').innerHTML=v.map(card).join('')||'<div>No destinations match.</div>';$('visibleCount').textContent=v.length;$('countLabel').textContent=`${v.length} verified access paths shown`;$('arrivalLabel').textContent=fmt(arrMs());$('requiredLabel').textContent=req().toFixed(1)+' ft';$('passage').style.display=region==='all'?'grid':'none';$('mapTitle').textContent=region==='fairfield'?'Fairfield County':region==='monmouth'?'Monmouth County':'All waters';$('mapSubtitle').textContent=region==='all'?'Fairfield County + Monmouth County':region==='fairfield'?'Greenwich → Stratford':'Atlantic Highlands → Brielle';syncMap(v)}
function initMap(){map=L.map('map',{zoomControl:true}).setView([40.65,-73.75],8);L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:19,attribution:'© OpenStreetMap'}).addTo(map);L.tileLayer('https://tiles.openseamap.org/seamark/{z}/{x}/{y}.png',{maxZoom:18,opacity:.85,attribution:'© OpenSeaMap'}).addTo(map);P.forEach(p=>{const icon=L.divIcon({className:'',html:`<div class="marker ${p.r}"><i></i></div>`,iconSize:[22,22],iconAnchor:[11,22]});markers[p.r+':'+p.id]=L.marker([p.lat,p.lon],{icon}).bindPopup(`<div class="popupname">${p.name}</div><div class="popupmeta">${p.town} · ${p.water}</div>`).addTo(map)});L.polyline([[41.06,-73.65],[40.86,-73.79],[40.79,-73.91],[40.70,-74.01],[40.57,-74.01],[40.42,-74.01]],{dashArray:'8 10',color:'#667f84',weight:2,opacity:.45}).addTo(map);render()}
function syncMap(v){if(!map)return;const ids=new Set(v.map(p=>p.r+':'+p.id));Object.entries(markers).forEach(([id,m])=>{if(ids.has(id)){if(!map.hasLayer(m))m.addTo(map)}else if(map.hasLayer(m))map.removeLayer(m)});if(v.length){const b=L.latLngBounds(v.map(p=>[p.lat,p.lon]));map.fitBounds(b.pad(.12),{maxZoom:12})}}
window.focusPlace=id=>{const p=P.find(x=>x.r+':'+x.id===id);if(p){map.setView([p.lat,p.lon],15);markers[id]?.openPopup();$('map').scrollIntoView({behavior:'smooth',block:'center'})}};
async function loadTides(){const needed=[...new Set(visible().map(p=>p.s))];let ok=0;await Promise.all(needed.map(async k=>{try{await fetchTide(k);ok++}catch{tideCache[k]={points:[],mode:'error'}}}));$('feedCount').textContent=`${ok}/${needed.length} live`;render()}
function setRegion(r){region=r;document.querySelectorAll('.regionbtn').forEach(b=>b.classList.toggle('active',b.dataset.region===r));const u=new URL(location.href);r==='all'?u.searchParams.delete('region'):u.searchParams.set('region',r);history.replaceState(null,'',u);render();loadTides()}
$('arrival').value=defaultArrival();const qp=new URLSearchParams(location.search).get('region');if(qp==='fairfield'||qp==='monmouth')region=qp;document.querySelectorAll('.regionbtn').forEach(b=>{b.classList.toggle('active',b.dataset.region===region);b.addEventListener('click',()=>setRegion(b.dataset.region))});$('search').addEventListener('input',render);['draft','ukc'].forEach(id=>$(id).addEventListener('input',render));$('arrival').addEventListener('change',loadTides);initMap();loadTides();setInterval(loadTides,600000);